### ISSUE TITLE
Implementation of sidebar elements

### ISSUE THREAD

**Issue by acoleman** [unlcms/unl_four#4]
Need to display sidebar first, sidebar second, and other shared page elements (that work with Book pages, etc)

(see: http://unlcms.unl.edu/fpa/music/doctoral-handbook)

**Comment by mfairchild365** [comment]
It looks like the issue with the text overflowing into the navigation sidebar is due to the use of the `wdn-inner-wrapper` class on the content of the node.  This class has a `width` of 60rem.  If you change that to a `max-width` of 60rem, the overflow problem is fixed.  To me this sounds like a WDN template issue rather than a theme issue.

**Comment by kabel** [comment]
You cannot and should not use `wdn-band` or `wdn-inner-wrapper` inside of a grid column.
